<Button>:
    front_size: 40
    color: 0.3,0.6,0.7,1
    size_hint: 0.3, 0.5

<FloatLayout>:
    Button:
        #pos_hint: {"x", "y", "top", "bottom", "left", "right"}
        pos_hint: {"x": 0.5, "top": 1}
        text: "Moooooooooooooin"

    Button:
        id: btn
        pos_hint: {"y": 0.3}
        text: "Meisteeeeeeeer" if btn.state == "normal" else "Down"
        background_color: 0.4,0.4,0.5,1
